AWSTemplateFormatVersion: 2010-09-09
Description: 'RAG Router Workshop'
Parameters:
  DeploymentArtifactsS3BucketName:
    Description: The S3 bucket that contains the artifacts for deployment
    Type: String
    Default: <Your S3 bucket name that contains this file - py312_opensearch-py_requests_and_requests-aws4auth.zip>
  LambdaLayerS3FileKey:
    Description: The name of the zip file in S3 that contains the Lambda Layer content
    Type: String
    Default: py312_opensearch-py_requests_and_requests-aws4auth.zip
  CodeRepositoryURL:
    Description: The URL to the code repository
    Type: String
    Default: https://github.com/aws-samples/advanced-rag-router-with-amazon-bedrock
Resources:
  WorkshopS3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ Ref: AWS::AccountId, "rag-router-bkt-1" ] ]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
  WorkshopS3Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "-", [ Ref: AWS::AccountId, "rag-router-bkt-2" ] ]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
  AOSSExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "RAGRouter-AOSSExecutionRole"
      Description: AOSS execution role for rag-router collection
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - opensearch.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/IAMFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonBedrockFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchFullAccessV2'        
      Policies:
        - PolicyName: aossrolepolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - aoss:APIAccessAll
                Resource:
                  - !Join [ "", [ "arn:aws:aoss:", !Ref AWS::Region, ":", !Ref AWS::AccountId, ":collection/*" ] ]
                  - !Join [ "", [ "arn:aws:aoss:", !Ref AWS::Region, ":", !Ref AWS::AccountId, ":index/*/*" ] ]
    DependsOn:
      - WorkshopS3Bucket1
      - WorkshopS3Bucket2
  AOSSIndexCreationLambdaFunctionExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "RAGRouter-AOICLambdaFunctionExecutionRole"
      Description: Lambda execution role for rag-router
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/CloudWatchFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchFullAccessV2'
      Policies:
        - PolicyName: lambdarolepolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - aoss:APIAccessAll
                Resource:
                  - !Join [ "", [ "arn:aws:aoss:", !Ref AWS::Region, ":", !Ref AWS::AccountId, ":collection/*" ] ]
                  - !Join [ "", [ "arn:aws:aoss:", !Ref AWS::Region, ":", !Ref AWS::AccountId, ":index/*/*" ] ]
  BedrockAndSMExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "RAGRouter-BedrockAndSMExecutionRole"
      Description: Bedrock and SM notebook execution role for rag-router
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
                - bedrock.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/IAMFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonBedrockFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSageMakerFullAccess'
        - 'arn:aws:iam::aws:policy/AWSCodeCommitFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchFullAccessV2' 
      Policies:
        - PolicyName: bedrockandsmrolepolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - aoss:APIAccessAll
                Resource:
                  - !Join [ "", [ "arn:aws:aoss:", !Ref AWS::Region, ":", !Ref AWS::AccountId, ":collection/*" ] ]
                  - !Join [ "", [ "arn:aws:aoss:", !Ref AWS::Region, ":", !Ref AWS::AccountId, ":index/*/*" ] ]            
    DependsOn:
      - WorkshopS3Bucket1
      - WorkshopS3Bucket2
  AOSSDataAccessPolicy1:
    Type: 'AWS::OpenSearchServerless::AccessPolicy'
    Properties:
      Name: rag-router-dap-1
      Type: data
      Description: Data access policy for rag-router collection 1
      Policy: !Sub >-
        [{"Description":"Access for cfn user","Rules":[{"ResourceType":"index","Resource":["index/rag-router-collection-1/*"],"Permission":["aoss:*"]},
        {"ResourceType":"collection","Resource":["collection/rag-router-collection-1"],"Permission":["aoss:*"]}],
        "Principal":["arn:aws:iam::${AWS::AccountId}:role/RAGRouter-AOSSExecutionRole", "arn:aws:iam::${AWS::AccountId}:role/RAGRouter-BedrockAndSMExecutionRole",
        "arn:aws:iam::${AWS::AccountId}:role/RAGRouter-AOICLambdaFunctionExecutionRole"]}]
    DependsOn:
      - AOSSExecutionRole
      - AOSSIndexCreationLambdaFunctionExecutionRole
      - BedrockAndSMExecutionRole
  AOSSNetworkPolicy1:
    Type: 'AWS::OpenSearchServerless::SecurityPolicy'
    Properties:
      Name: rag-router-np-1
      Type: network
      Description: Network policy for rag-router collection 1
      Policy: >-
        [{"Rules":[{"ResourceType":"collection","Resource":["collection/rag-router-collection-1"]}, {"ResourceType":"dashboard","Resource":["collection/rag-router-collection-1"]}],"AllowFromPublic":true}]
  AOSSEncryptionPolicy1:
    Type: 'AWS::OpenSearchServerless::SecurityPolicy'
    Properties:
      Name: rag-router-sp-1
      Type: encryption
      Description: Encryption policy for rag-router collection 1
      Policy: >-
        {"Rules":[{"ResourceType":"collection","Resource":["collection/rag-router-collection-1"]}],"AWSOwnedKey":true}
  AOSSDataAccessPolicy2:
    Type: 'AWS::OpenSearchServerless::AccessPolicy'
    Properties:
      Name: rag-router-dap-2
      Type: data
      Description: Data access policy for rag-router collection 2
      Policy: !Sub >-
        [{"Description":"Access for cfn user","Rules":[{"ResourceType":"index","Resource":["index/rag-router-collection-2/*"],"Permission":["aoss:*"]},
        {"ResourceType":"collection","Resource":["collection/rag-router-collection-2"],"Permission":["aoss:*"]}],
        "Principal":["arn:aws:iam::${AWS::AccountId}:role/RAGRouter-AOSSExecutionRole", "arn:aws:iam::${AWS::AccountId}:role/RAGRouter-BedrockAndSMExecutionRole",
        "arn:aws:iam::${AWS::AccountId}:role/RAGRouter-AOICLambdaFunctionExecutionRole"]}]
    DependsOn:
      - AOSSExecutionRole
      - AOSSIndexCreationLambdaFunctionExecutionRole
      - BedrockAndSMExecutionRole
  AOSSNetworkPolicy2:
    Type: 'AWS::OpenSearchServerless::SecurityPolicy'
    Properties:
      Name: rag-router-np-2
      Type: network
      Description: Network policy for rag-router collection 2
      Policy: >-
        [{"Rules":[{"ResourceType":"collection","Resource":["collection/rag-router-collection-2"]}, {"ResourceType":"dashboard","Resource":["collection/rag-router-collection-2"]}],"AllowFromPublic":true}]
  AOSSEncryptionPolicy2:
    Type: 'AWS::OpenSearchServerless::SecurityPolicy'
    Properties:
      Name: rag-router-sp-2
      Type: encryption
      Description: Encryption policy for rag-router collection 2
      Policy: >-
        {"Rules":[{"ResourceType":"collection","Resource":["collection/rag-router-collection-2"]}],"AWSOwnedKey":true}
  AOSSCollection1:
    Type: 'AWS::OpenSearchServerless::Collection'
    Properties:
      Name: rag-router-collection-1
      Type: VECTORSEARCH
      Description: Collection 1 to hold the embeddings for the content to query
    DependsOn:
      - AOSSEncryptionPolicy1
      - AOSSNetworkPolicy1
      - AOSSDataAccessPolicy1
  AOSSCollection2:
    Type: 'AWS::OpenSearchServerless::Collection'
    Properties:
      Name: rag-router-collection-2
      Type: VECTORSEARCH
      Description: Collection 2 to hold the embeddings for the content to query
    DependsOn:
      - AOSSEncryptionPolicy2
      - AOSSNetworkPolicy2
      - AOSSDataAccessPolicy2
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: rag-router-py312_opensearch-py_requests_and_requests-aws4auth
      Description: Python 3.12 opensearch-py, requests and requests-aws4auth packages
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.12
      Content:
        S3Bucket:
          Ref: DeploymentArtifactsS3BucketName
        S3Key:
          Ref: LambdaLayerS3FileKey
  AOSSIndexCreationLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Function to create the AOSS Index
      Handler: index.lambda_handler
      FunctionName: rag-router-aoss-index-creation
      MemorySize: 128
      Runtime: python3.12
      Role: !GetAtt AOSSIndexCreationLambdaFunctionExecutionRole.Arn
      Timeout: 240
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
          AOSSCOLLECTIONID1: !GetAtt AOSSCollection1.Id
          AOSSCOLLECTIONID2: !GetAtt AOSSCollection2.Id
          AOSSINDEXNAME: rag-router-index
      Code:
        ZipFile: |
          import botocore.session
          from botocore.credentials import Credentials
          import cfnresponse
          import json
          from opensearchpy import OpenSearch, RequestsHttpConnection, AWSV4SignerAuth
          import os
          import time


          # Function to create the OpenSearch client for AOSS
          def get_os_client(region, collection_id):
              host = "{}.{}.aoss.amazonaws.com".format(collection_id, region)
              # Get the credentials from the boto3 session
              credentials = botocore.session.Session().get_credentials()
              auth = AWSV4SignerAuth(credentials, region, 'aoss')
              # Create an OpenSearch client and use the request-signer
              os_client = OpenSearch(
                  hosts=[{'host': host, 'port': 443}],
                  http_auth=auth,
                  use_ssl=True,
                  verify_certs=True,
                  connection_class=RequestsHttpConnection,
                  pool_maxsize=20,
                  timeout=3000
              )
              return os_client


          # Function to create the OpenSearch index
          def create_index(aoss_py_client, index_name):
              knn_index = {
                  "settings": {
                      "index.knn": True,
                  },
                  "mappings": {
                      "properties": {
                          "vector": {
                              "type": "knn_vector",
                              "dimension": 1536,
                              "method": {
                                "engine": "faiss",
                                "name": "hnsw"
                              }
                          },
                          "text": {
                              "type": "text"
                          },
                          "metadata": {
                              "type": "text"
                          }
                      }
                  }
              }
              aoss_py_client.indices.create(index=index_name, body=knn_index, ignore=400)


          # Function to delete the OpenSearch index
          def delete_index(aoss_py_client, index_name):
              aoss_py_client.indices.delete(index=index_name, ignore=400)


           # Lambda handler function
          def lambda_handler(event, context):
              response_data = {}
              response_data['Data'] = ''
              print(event)
              print(context)
              physical_record_id = context.log_group_name
              try:
                  # Get the input parameters
                  region = os.environ['REGION']
                  collection_1_id = os.environ['AOSSCOLLECTIONID1']
                  collection_2_id = os.environ['AOSSCOLLECTIONID2']
                  index_name = os.environ['AOSSINDEXNAME']
                  # Create the clients
                  aoss_py_client_1 = get_os_client(region, collection_1_id)
                  aoss_py_client_2 = get_os_client(region, collection_2_id)
                  # Process based on event type
                  if event['RequestType'] == 'Create':
                      # Create the AOSS indexes
                      print('Creating the AOSS index "{}" in the collection "{}"...'.format(index_name, collection_1_id))
                      create_index(aoss_py_client_1, index_name)
                      print('Created the AOSS index "{}" in the collection "{}".'.format(index_name, collection_1_id))
                      print('Creating the AOSS index "{}" in the collection "{}"...'.format(index_name, collection_2_id))
                      create_index(aoss_py_client_2, index_name)
                      print('Created the AOSS index "{}" in the collection "{}".'.format(index_name, collection_2_id))
                      print('Waiting for 60 seconds...')
                      time.sleep(60)
                      print('Completed waiting for 60 seconds.')
                  elif event['RequestType'] == 'Delete':
                      # Delete the AOSS indexes
                      print('Deleting the AOSS index "{}" in the collection "{}"...'.format(index_name, collection_1_id))
                      delete_index(aoss_py_client_1, index_name)
                      print('Deleted the AOSS index "{}" in the collection "{}".'.format(index_name, collection_1_id))
                      print('Deleting the AOSS index "{}" in the collection "{}"...'.format(index_name, collection_2_id))
                      delete_index(aoss_py_client_2, index_name)
                      print('Deleted the AOSS index "{}" in the collection "{}".'.format(index_name, collection_2_id))
                      print('Waiting for 60 seconds...')
                      time.sleep(60)
                      print('Completed waiting for 60 seconds.')
                  else:
                      print('Skipped creating/deleting the AOSS index "{}" in the collection "{}".'.format(index_name, collection_1_id))
                      print('Skipped creating/deleting the AOSS index "{}" in the collection "{}".'.format(index_name, collection_2_id))
                  # Send the SUCCESS response to CloudFormation
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
              except Exception as exception:
                  print('Exception occurred :: {}'.format(exception))
                  # Send the FAILED response to CloudFormation
                  cfnresponse.send(event, context, cfnresponse.FAILED, response_data)
      Layers:
        - !GetAtt LambdaLayer.LayerVersionArn
    DependsOn:
      - AOSSCollection1
      - AOSSCollection2
      - LambdaLayer
      - AOSSIndexCreationLambdaFunctionExecutionRole
  AOSSIndexCreationLambdaFunctionInvoke:
    Type: AWS::CloudFormation::CustomResource
    Version: "1.0"
    Properties:
      ServiceToken: !GetAtt AOSSIndexCreationLambdaFunction.Arn
    DependsOn:
      - AOSSIndexCreationLambdaFunction
  BedrockKB1:
    Type: 'AWS::Bedrock::KnowledgeBase'
    Properties:
      Name: rag-router-kb-1
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Join [ "", [ "arn:aws:bedrock:", !Ref AWS::Region, "::foundation-model/amazon.titan-embed-text-v1" ] ]
      StorageConfiguration:
        OpensearchServerlessConfiguration:
          CollectionArn: !GetAtt AOSSCollection1.Arn
          FieldMapping:
            MetadataField: metadata
            TextField: text
            VectorField: vector
          VectorIndexName: rag-router-index
        Type: OPENSEARCH_SERVERLESS
      RoleArn: !GetAtt BedrockAndSMExecutionRole.Arn
      Description: Knowledge Base 1 to provide the RAG capability
    DependsOn:
      - AOSSCollection1
      - AOSSIndexCreationLambdaFunctionInvoke
      - WorkshopS3Bucket1
      - BedrockAndSMExecutionRole
  BedrockKB2:
    Type: 'AWS::Bedrock::KnowledgeBase'
    Properties:
      Name: rag-router-kb-2
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Join [ "", [ "arn:aws:bedrock:", !Ref AWS::Region, "::foundation-model/amazon.titan-embed-text-v1" ] ]
      StorageConfiguration:
        OpensearchServerlessConfiguration:
          CollectionArn: !GetAtt AOSSCollection2.Arn
          FieldMapping:
            MetadataField: metadata
            TextField: text
            VectorField: vector
          VectorIndexName: rag-router-index
        Type: OPENSEARCH_SERVERLESS
      RoleArn: !GetAtt BedrockAndSMExecutionRole.Arn
      Description: Knowledge Base 2 to provide the RAG capability
    DependsOn:
      - AOSSCollection2
      - AOSSIndexCreationLambdaFunctionInvoke
      - WorkshopS3Bucket2
      - BedrockAndSMExecutionRole
  BedrockKB1DataSource:
    Type: AWS::Bedrock::DataSource
    Properties:
      Name: rag-router-kb-1-ds-1
      Description: Data Source for the Knowledge Base 1 that provides the RAG capability
      KnowledgeBaseId: !GetAtt BedrockKB1.KnowledgeBaseId
      DataSourceConfiguration:
        S3Configuration:
          BucketArn: !GetAtt WorkshopS3Bucket1.Arn
        Type: S3
    DependsOn:
      - BedrockKB1
  BedrockKB2DataSource:
    Type: AWS::Bedrock::DataSource
    Properties:
      Name: rag-router-kb-2-ds-1
      Description: Data Source for the Knowledge Base 2 that provides the RAG capability
      KnowledgeBaseId: !GetAtt BedrockKB2.KnowledgeBaseId
      DataSourceConfiguration:
        S3Configuration:
          BucketArn: !GetAtt WorkshopS3Bucket2.Arn
        Type: S3
    DependsOn:
      - BedrockKB2
  CodeRepository:
    Type: AWS::SageMaker::CodeRepository
    Properties:
      GitConfig:
          RepositoryUrl:
            Ref: CodeRepositoryURL
  SMNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: rag-router-instance
      PlatformIdentifier: notebook-al2-v2
      InstanceType: ml.t3.medium
      RoleArn: !GetAtt BedrockAndSMExecutionRole.Arn
      DefaultCodeRepository: !GetAtt CodeRepository.CodeRepositoryName
    DependsOn:
      - BedrockAndSMExecutionRole
      - CodeRepository